apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-ranger-admin
  labels:
    app: apache-ranger
    component: apache-ranger-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-ranger
      component: apache-ranger-admin
  template:
    metadata:
      labels:
        app: apache-ranger
        component: apache-ranger-admin
    spec:
      containers:
        - name: apache-ranger-admin
          image: ranger:dev
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
          ports:
            - name: http
              containerPort: 6080
              protocol: TCP
      securityContext:
        runAsUser: 0
        runAsGroup: 0