apiVersion: v1
kind: Service
metadata:
  name: ranger-admin
  labels:
    app: apache-ranger
    component: apache-ranger-admin
spec:
  type: ClusterIP
  ports:
    - port: 6080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: apache-ranger
    component: apache-ranger-admin