version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: es01
    hostname: es01
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - 9200:9200
    volumes:
    - ranger-es-data:/usr/share/elasticsearch/data
  postgresql:
    image: postgres:13
    container_name: psql01
    hostname: psql01
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
    - ranger-pg-data:/var/lib/postgresql/data
  ranger-admin:
    build: 
      context: ./ranger-admin
      dockerfile: Dockerfile
    container_name: ranger-admin
    hostname: ranger-admin
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 6G
        reservations:
          cpus: '1'
          memory: 5G
    ports:
      - 6080:6080
  trino:
    build: 
      context: ./trino
      dockerfile: Dockerfile
    hostname: localhost-trino
    user: root
    container_name: localhost-trino
    ports:
      - 8080:8080
      - 8443:8443
volumes:
  ranger-es-data:
  ranger-pg-data:
