apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranger-solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ranger-solr
  template:
    metadata:
      labels:
        app: ranger-solr
    spec:
      containers:
      - name: ranger-solr
        image: ranger-solr:k8s
        ports:
        - containerPort: 8983
        volumeMounts:
        - name: ranger-solr-config-elevate
          mountPath: /opt/solr/server/solr/configsets/ranger_audits/conf/elevate.xml
          subPath: elevate.xml
        args:
        - solr-precreate
        - ranger_audits
        - /opt/solr/server/solr/configsets/ranger_audits
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
      volumes:
      - name: ranger-solr-config-elevate
        configMap:
          name: ranger-solr-config-elevate
