apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-coordinator-dev-config-volume
data:
  config.properties: |-
    coordinator=true
    node-scheduler.include-coordinator=true
    http-server.http.port=8080
    query.max-memory=2GB
    query.max-memory-per-node=1GB
    discovery.uri=http://localhost:8080
    http-server.process-forwarded=true
    http-server.authentication.allow-insecure-over-http=true
    internal-communication.shared-secret=acN0eEVueRJVGkQ1djBFh9A6OU0+Utk+UMYzSPOO0W+OcC8yOQNE3+mcWi8dXbBvGHYZn7YijpIYHH5Ur15u+nB2358T/V0X1uevpIaS0JvJtL8Jhd6V+WX6pKP7bHGdGWdwvnpBU+FiogCRWNpdtOwvNgHQTMd4HNqGZp4rr2+RGOlYOB8GyMQ5K7zb08JT4NenB6eVvUG090+kxRyi0Ln2S2aBuvTPOkO3dpmiUcs3WcAfzwxN1TJEf+V2ZQu3ohj8+6YGSt+XXVcSOxNICDHMTdzEYkjtDS4/64+JosFi0E5tL2QVZgUj1kGL+npQ52qS7KqUNXM+0hRyfyIq0zesr72dzwjZiZLxrOxsbduDofabKjhzjU4Xv2i9J46nmzSXFUATi5rfwHn+Ac/DgXQZ41ntzMqD6lHUk0ttGS/aE//WIYLmsFF1WSWL33nWKCxv4u/j67yilH9Ejb0PIvq9MLUsFQPvhcq2k+eCxKmKWHkZ8jNWib42Rpjm2DDaXcXxt95K5bzJHozYUpsi82AOpOgEy6x7kqWBLQ0m4hdfnWzQ0qBaJiY/XDWxflucr6jz3o/XpC1xO1HH1DWnwVM3h7geFg2h/2WuIuV0cND8r7Pl2qku/uUWdqPqJI8YasaGw9KYm+LHLPmp1lX3bQvb9QHLDZAS6EGe5t4Aat8=
    web-ui.enabled=true
  exchange-manager.properties: |-
    exchange-manager.name=filesystem
    exchange.base-directories=/tmp/trino-local-file-system-exchange-manager
  jvm.config: |-
    -server
    -agentpath:/usr/lib/trino/bin/libjvmkill.so
    -Xmx4G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -XX:-OmitStackTraceInFastThrow
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
    # Allow loading dynamic agent used by JOL
    -XX:+EnableDynamicAgentLoading
  log.properties: io.trino=INFO
  node.properties: |-
    node.environment=production
    node.data-dir=/data/trino
    plugin.dir=/usr/lib/trino/plugin

