apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trino-coordinator-dev
  name: trino-coordinator-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino-coordinator-dev
  template:
    metadata:
      labels:
        app: trino-coordinator-dev
    spec:
      containers:
      - image: ranger-trino:dev6
        imagePullPolicy: IfNotPresent
        name: trino-coordinator-dev
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - mountPath: /etc/trino/config.properties
          name: config-coordinator
          subPath: config.properties
        - mountPath: /etc/trino/log.properties
          name: config-coordinator
          subPath: log.properties
        - mountPath: /etc/trino/node.properties
          name: config-coordinator
          subPath: node.properties
        - mountPath: /etc/trino/catalog
          name: catalog-volume
      restartPolicy: Always
      securityContext: 
        runAsUser: 0
        runAsGroup: 0
      volumes:
      - configMap:
          name: trino-coordinator-dev-config-volume
        name: config-coordinator
      - configMap:
          name: trino-catalog-dev-config-volume
        name: catalog-volume