apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-coordinator-dev-config-volume
data:
  config.properties: |-
    coordinator=true
    node-scheduler.include-coordinator=true
    http-server.http.port=8080
    discovery.uri=http://localhost:8080
  # exchange-manager.properties: |-
  #   exchange-manager.name=filesystem
  #   exchange.base-directories=/tmp/trino-local-file-system-exchange-manager
  jvm.config: |-
    -server
    -Xmx1G
    -XX:InitialRAMPercentage=80
    -XX:MaxRAMPercentage=80
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+ExitOnOutOfMemoryError
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:-OmitStackTraceInFastThrow
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
    -Dfile.encoding=UTF-8
    # Allow loading dynamic agent used by JOL
    -XX:+EnableDynamicAgentLoading
    # https://bugs.openjdk.org/browse/JDK-8329528
    -XX:+UnlockDiagnosticVMOptions
    -XX:G1NumCollectionsKeepPinned=10000000
  log.properties: io.trino=INFO
  node.properties: |-
    node.environment=production
    node.data-dir=/var/trino/data

