apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trino-coordinator-dev
  name: trino-coordinator-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino-coordinator-dev
  template:
    metadata:
      labels:
        app: trino-coordinator-dev
    spec:
      containers:
        image: trinodb/trino:452
        imagePullPolicy: IfNotPresent
        name: trino-coordinator-dev
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
        volumeMounts:
        - mountPath: /etc/trino
          name: config-volume
        - mountPath: /etc/trino/catalog
          name: catalog-volume
        - mountPath: /opt/security/password.db
          name: password-secret
          readOnly: true
          subPath: password.db
        - mountPath: /opt/security/group.txt
          name: password-secret
          readOnly: true
          subPath: group.txt
        - mountPath: /opt/security/rules.json
          name: password-secret
          readOnly: true
          subPath: rules.json
      restartPolicy: Always
      securityContext: 
        runAsUser: 0
      volumes:
      - configMap:
          defaultMode: 420
          name: trino-coordinator-dev-config-volume
        name: config-volume
      - configMap:
          defaultMode: 420
          name: trino-catalog-dev-config-volume
        name: catalog-volume
      - name: password-secret
        secret:
          defaultMode: 420
          secretName: trino-secrets
