apiVersion: v1
kind: Service
metadata:
  name: ranger-trino
  labels:
    app: trino-coordinator-dev
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    # - name: https
    #   port: 443
    #   protocol: TCP
    #   targetPort: 8080
  selector:
    app: trino-coordinator-dev