apiVersion: v1
kind: Service
metadata:
  name: ranger-trino1
  labels:
    app: trino-coordinator-dev
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: trino-coordinator-dev