apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trino-worker-dev
  name: trino-worker-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino-worker-dev
  template:
    metadata:
      labels:
        app: trino-worker-dev
    spec:
      containers:
      - image: trinodb/trino:451
        imagePullPolicy: IfNotPresent
        name: trino-worker-dev
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/trino
          name: config-volume-dev
        - mountPath: /etc/trino/catalog
          name: catalog-volume
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
      securityContext: 
        runAsUser: 0
      volumes:
      - configMap:
          defaultMode: 420
          name: trino-worker-dev-config-volume
        name: config-volume-dev
      - configMap:
          defaultMode: 420
          name: trino-catalog-dev-config-volume
        name: catalog-volume
